apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: ceph-volsync-plugin-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Ceph VolSync Plugin Operator acts on VolSync's Custom Resources but
    uses Ceph's internal mechanisms to perform significantly more efficient data replication.
  displayName: Ceph VolSync Plugin Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ceph-volsync-plugin-operator
  - data
  - csi
  - disaster recovery
  - replication
  - storage
  - backup
  - ceph
  links:
  - name: Ceph Volsync Plugin Operator
    url: https://ceph-volsync-plugin-operator.domain
  maintainers:
  - email: rar@redhat.com
    name: Rakshith R
  - email: mrajanna@redhat.com
    name: Madhu Rajanna
  maturity: alpha
  provider:
    name: Red Hat, Inc.
    url: github.com/RamenDR/ceph-volsync-plugin
  version: 0.0.0
