apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ceph-volsync-plugin-operator.clusterserviceversion.yaml
commonAnnotations:
  olm.skipRange: ""
patches:
- patch: '[{"op": "replace", "path": "/spec/replaces", "value": ""}]'
  target:
    kind: ClusterServiceVersion
    name: ceph-volsync-plugin-operator.v0.0.1
